print("\n")
input("Click ENTER to start the game.")
print("\n")
import time
import random
def td(m,t=0.05):
   for l in m:
        print(l,end='',flush=True)
        time.sleep(t) 

def end():
    td("\n\nGame Over\n",0.15)
    td("Thank You for playing Hand-Cricket!!\n",0.15)
    print("\n")
    exit()


def scr():
    print("\n\n")
    td("The Match is over!!\n")
    td("\nYour Score is : ")
    print(ps)
    td("\nComputer's Score is : ")
    print(cs)
    if(ps>cs):
        print("\n")
        td("You WIN!!\nJUST A DUMB LUCK",0.15)
        print("\n\n")
        end()
    elif(ps<cs):
        print("\n")
        td("You LOSE!!\nHA HA",0.15)
        print("\n\n")
        end()
    else:
        print("\n")
        td("Its a TIE!!\nAWWWW",0.15)
        print("\n\n")
        end()
    



#Welcome message
td("Hello\n",0.12)
td("Welcome to the game of Hand-Cricket!\n",0.07)
td("Here your Opponent is Me : The computer\n",0.07)
# Toss
td("Lets toss")
print("\n")
td("Enter H for choosing heads OR enter T for tails : ")
t1=input()
t2=random.randint(0,1)
if(t2==1):                                     #heads is 1
    td("\nIt's a Head!!")                       
else:
    td("\nIt's Tails!")                        #tails is 0

if(t1=='h'or t1=='H'):
    print("\n")
    tt=1
else:
    print("\n")
    tt=0

if(tt==t2):
    td("You won the toss!\n")
    td("You Choose to Bat OR Ball!\n")
    td("Enter Bat for Batting or Ball for Balling\n")
    ch=input()
    if(ch=='Bat' or ch=='bat'):
        td("\nYou Choose Batting!\n")
        c=1
    else:
        td("\nYou Choose Balling!\n")
        c=0
else:
    td("You lost the toss !\n")
    td("Computer Chooses to Bat OR Ball\n")
    ta=random.randint(0,1)
    if(ta==0):
        td("Computer chose Batting !\n")
        c=0
    else:
        td("Computer chose Balling !\n")
        c= 1

if(c==1):
    td("\nYour time to Bat \n")
    td("Computer will ball\n")
    td("\nRule: \nEnter your number from 0 to 6\n")
    td("If your number matches with random number generated by the Computer\n")
    td("You will be out\n")
    td("If you enter 0 then the number generated by the computer will be added\n")
    td("\nAll the Best !!\n\n")
    c1=1
    ps=0
    b1=0
    while(b1!=c1):
        td("Enter your number: \n",0.03)
        b1=int(input())
        c1=random.randint(0,6)
        td("Computer's number: \n",0.03)
        print(c1)
        if(b1==c1):
            break
        elif(b1==1 or b1==2 or b1==3 or b1==4 or b1==5 or b1==6):
            ps+=b1
            continue
        elif(b1==0):
            ps+=c1
            continue
        else:
            td("Invalid input!! Try again\n")
            continue
    td("You are out!!\n")
    td("Your score is: ")
    print(ps)
    td("Score required for the computer to win : ")
    print(ps+1)
    print("\n")
    td("\nComputers time to bat\n")
    td("You will ball\n")
    td("\nRule: \nEnter your number from 0 to 6\n")
    td("If your number matches with random number generated by the Computer\n")
    td("Computer will be out\n")
    td("If you enter 0 then the number generated by the computer will be added\n")
    td("\nAll the Best !!\n\n")
    c1=0
    cs=0
    b1=1
    while(b1!=c1):
        if(cs>ps):
            td("Computer's score is: ")
            print(cs)
            scr()
        td("Enter your number: \n",0.03)
        b1=int(input())
        c1=random.randint(0,6)
        td("Computer's number: \n",0.03)
        print(c1)
        if(b1==0 or b1==1 or b1==2 or b1==3 or b1==4 or b1==5 or b1==6):
            if(c1==b1):
                break
            elif(c1==1 or c1==2 or c1==3 or c1==4 or c1==5 or c1==6):
                cs+=c1
                continue
            elif(c1==0):
                cs+=b1
                continue
        else:
            td("Invalid input!! Try again\n")
            continue
    td("Computer is out!!\n")
    td("Computer's score is: ")
    print(cs)
    scr()
else:
    td("\nComputers time to bat\n")
    td("You will ball\n")
    td("\nRule: \nEnter your number from 0 to 6\n")
    td("If your number matches with random number generated by the Computer\n")
    td("Computer will be out\n")
    td("If the computer generates the number 0 then your input number will be added\n")
    td("\nAll the Best !!\n\n")
    c1=0
    cs=0
    b1=1
    while(b1!=c1):
        td("Enter your number: \n",0.03)
        b1=int(input())
        c1=random.randint(0,6)
        td("Computer's number: \n",0.03)
        print(c1)
        if(b1==0 or b1==1 or b1==2 or b1==3 or b1==4 or b1==5 or b1==6):
            if(c1==b1):
                break
            elif(c1==1 or c1==2 or c1==3 or c1==4 or c1==5 or c1==6):
                cs+=c1
                continue
            elif(c1==0):
                cs+=b1
                continue
        else:
            td("Invalid input!! Try again\n")
            continue
    td("Computer is out!!\n")
    td("Computer's score is: ")
    print(cs)
    td("Score required for YOU to win : ")
    print(cs+1)
    td("\nYour time to Bat \n")
    td("Computer will ball\n")
    td("\nRule: Enter your number from 0 to 6\n")
    td("If your number matches with random number generated by the Computer\n")
    td("You will be out\n")
    td("If you enter 0 then the number generated by the computer will be added\n")
    td("\nAll the Best !!\n\n")
    c1=1
    ps=0
    b1=0
    while(b1!=c1):
        if(ps>cs):
            td("Your score is: ")
            print(ps)
            scr()
        td("Enter your number: \n",0.03)
        b1=int(input())
        c1=random.randint(0,6)
        td("Computer's number: \n",0.03)
        print(c1)
        if(b1==c1):
            break
        elif(b1==1 or b1==2 or b1==3 or b1==4 or b1==5 or b1==6):
            ps+=b1
            continue
        elif(b1==0):
            ps+=c1
            continue
        else:
            td("Invalid input!! Try again\n")
            continue
    td("You are out!!\n")
    td("Your score is: ")
    print(ps)
    scr()


